pipeline {
    agent none
    
    stages {
        stage('Build') {
            agent {
                any {
                    image 'node:latest'
                    args '-p 3000:3000'
                }
            }
            steps {
                sh '/usr/bin/npm install'
            }
        }
    }
}