pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                any {
                    image 'node:6-alpine'
                    args '-p 3000:3000'
                }
            }
            steps {
                sh 'npm install'
            }
        }
    }
}